[package]
name = "yellow-pitaya"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
cairo-rs = "0.8"
env_logger = "0.7"
glib = "0.9"
gdk = "0.12"
log = "0.4"
redpitaya-scpi = "0.27"
relm = "0.19"
relm-derive = "0.19"
structopt = "0.3"

[dependencies.gtk]
version = "0.8"
features = ["v3_16"]
