[package]
name = "yellow-pitaya"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
cairo-rs = "0.1"
docopt = "0.8"
env_logger = "0.4"
glib = "0.1"
gdk = "0.5"
gdk-sys = "0.3"
gtk-sys = "0.3"
log = "0.3"
redpitaya-scpi = "0.27"
relm = "0.9"
relm-core = "0.1"
relm-attributes = "0.9"
relm-derive = "0.9"
serde = "1.0"
serde_derive = "1.0"

[dependencies.gtk]
version = "0.1"
features = ["v3_14"]
